export { LoginPage } from './Login'
export { DashboardPage } from './Dashboard'
export { QrCodePage } from './QrCode'
export { QrScanPage } from './QrScan'
export { AttendanceHistory as AttendanceHistoryPage } from './AttendanceHistory'
export { ShiftsPage } from './Shifts'
export { SalaryConfigPage } from './SalaryConfig'
export { SalaryReportPage } from './SalaryReport'
export { UsersPage } from './Users'
export { SettingsPage } from './Settings'
export { LeaveRequestsPage } from './LeaveRequests'
export { LeaveApproval as LeaveApprovalPage } from './LeaveApproval'
